name: Build and Push to ECR

on:
  push:
    branches: [master, develop, main]
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: 921436147132.dkr.ecr.us-east-1.amazonaws.com
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository

jobs:
  # Build and push Docker images (build JARs in each job)
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - service_name: registration-processor-workflow-manager-service
            service_path: registration-processor/workflow-engine/registration-processor-workflow-manager-service
            port: 8081
          - service_name: registration-processor-stage-group-1
            service_path: registration-processor/stage-groups/registration-processor-stage-group-1
            port: 8081
          - service_name: registration-processor-registration-status-service
            service_path: registration-processor/init/registration-processor-registration-status-service
            port: 8081
          - service_name: registration-processor-notification-service
            service_path: registration-processor/registration-processor-notification-service
            port: 8081
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "temurin"

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build Maven project
        working-directory: ./registration-processor
        run: |
          mvn clean compile -DskipTests
          mvn package -DskipTests

      - name: Verify JAR file exists
        run: |
          echo "Looking for JAR file for ${{ matrix.service_name }}"
          echo "Current directory: $(pwd)"
          echo "Contents of registration-processor directory:"
          ls -la ./registration-processor/
          echo "Contents of service target directory:"
          ls -la ./${{ matrix.service_path }}/target/ || echo "Target directory not found"
          echo "Searching for JAR files:"
          find ./registration-processor -name "*${{ matrix.service_name }}*.jar" -type f | grep -v javadoc | grep -v sources
          JAR_FILE=$(find ./registration-processor -name "*${{ matrix.service_name }}*.jar" -type f | grep -v javadoc | grep -v sources | head -1)
          if [ -z "$JAR_FILE" ]; then
            echo "No JAR file found for ${{ matrix.service_name }}"
            echo "Available JAR files:"
            find ./registration-processor -name "*.jar" -type f | head -20
            echo "Checking if JAR files are in service target directory:"
            find ./${{ matrix.service_path }}/target/ -name "*.jar" -type f 2>/dev/null || echo "No JAR files in service target"
            exit 1
          fi
          echo "Found JAR file: $JAR_FILE"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Create ECR repository if not exists
        run: |
          aws ecr describe-repositories --repository-names mosip-${{ matrix.service_name }} --region ${{ env.AWS_REGION }} || \
          aws ecr create-repository --repository-name mosip-${{ matrix.service_name }} --region ${{ env.AWS_REGION }}

      - name: Build and push Docker image
        run: |
          # Find the main JAR file (not javadoc or sources)
          JAR_FILE=$(find ./registration-processor -name "*${{ matrix.service_name }}*.jar" -type f | grep -v javadoc | grep -v sources | head -1)

          if [ -z "$JAR_FILE" ]; then
            echo "No JAR file found for ${{ matrix.service_name }}"
            echo "Available JAR files:"
            find ./registration-processor -name "*.jar" -type f | head -20
            echo "Checking service target directory:"
            find ./${{ matrix.service_path }}/target/ -name "*.jar" -type f 2>/dev/null || echo "No JAR files in service target"
            exit 1
          fi

          echo "Found JAR file: $JAR_FILE"

          # Copy JAR file to service target directory if it's not already there
          SERVICE_TARGET_DIR="./${{ matrix.service_path }}/target"
          if [ ! -d "$SERVICE_TARGET_DIR" ]; then
            mkdir -p "$SERVICE_TARGET_DIR"
          fi
          
          # Copy the JAR file to the service target directory
          cp "$JAR_FILE" "$SERVICE_TARGET_DIR/"

          # List files in service target directory for debugging
          echo "Files in service target directory:"
          ls -la "$SERVICE_TARGET_DIR/"

          # Build Docker image from service directory
          cd ./${{ matrix.service_path }}
          docker build -t ${{ env.ECR_REGISTRY }}/mosip-${{ matrix.service_name }}:${{ github.sha }} .
          docker build -t ${{ env.ECR_REGISTRY }}/mosip-${{ matrix.service_name }}:latest .

          # Push to ECR
          docker push ${{ env.ECR_REGISTRY }}/mosip-${{ matrix.service_name }}:${{ github.sha }}
          docker push ${{ env.ECR_REGISTRY }}/mosip-${{ matrix.service_name }}:latest

          echo "Successfully built and pushed ${{ matrix.service_name }}"
          echo "Workflow version: 2025-01-03-fixed"
